files:
  - source: /**/en.editor_localization
    translation: /**/%locale_with_underscore%.editor_localization
    type: properties
    escape_special_characters: 0
    languages_mapping:
      ru-RU: ru
      en-EN: en